# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lib_api.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(823, 677)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget_main = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget_main.setIconSize(QtCore.QSize(5, 5))
        self.tabWidget_main.setObjectName("tabWidget_main")
        self.tab_all_main = QtWidgets.QWidget()
        self.tab_all_main.setObjectName("tab_all_main")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_all_main)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.listWidget = QtWidgets.QListWidget(self.tab_all_main)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout_2.addWidget(self.listWidget)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(8, 8, 8, 8)
        self.gridLayout.setSpacing(5)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_8 = QtWidgets.QPushButton(self.tab_all_main)
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout.addWidget(self.pushButton_8, 0, 1, 1, 1)
        self.btn_all_device_info = QtWidgets.QPushButton(self.tab_all_main)
        self.btn_all_device_info.setObjectName("btn_all_device_info")
        self.gridLayout.addWidget(self.btn_all_device_info, 0, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.tabWidget_main.addTab(self.tab_all_main, "")
        self.tab_fiscalizations_main = QtWidgets.QWidget()
        self.tab_fiscalizations_main.setObjectName("tab_fiscalizations_main")
        self.tabWidget_main.addTab(self.tab_fiscalizations_main, "")
        self.verticalLayout.addWidget(self.tabWidget_main)
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionprint_1 = QtWidgets.QAction(MainWindow)
        self.actionprint_1.setCheckable(True)
        self.actionprint_1.setObjectName("actionprint_1")

        self.retranslateUi(MainWindow)
        self.tabWidget_main.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tab_all_main.setToolTip(_translate("MainWindow", "<html><head/><body><p>hgjgh</p></body></html>"))
        self.tab_all_main.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>m,</p></body></html>"))
        self.pushButton_8.setText(_translate("MainWindow", "PushButton"))
        self.btn_all_device_info.setText(_translate("MainWindow", "ALL_device_info"))
        self.tabWidget_main.setTabText(self.tabWidget_main.indexOf(self.tab_all_main), _translate("MainWindow", "ALL"))
        self.tabWidget_main.setTabText(self.tabWidget_main.indexOf(self.tab_fiscalizations_main), _translate("MainWindow", "Fiscalize"))
        self.actionprint_1.setText(_translate("MainWindow", "print(\"1\")"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
